services:
  - type: web
    name: teromix-cms
    env: node
    buildCommand: cd teromix-cms && npm install && npm run build
    startCommand: cd teromix-cms && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        value: dpg-d0vlpegdl3ps73frb3gg-a.oregon-postgres.render.com
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: teromix_wvds
      - key: DATABASE_USERNAME
        value: teromix_user
      - key: DATABASE_PASSWORD
        value: k85ZVCKaZynyleZMczpmH2FrZP0POCCT
      - key: DATABASE_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: teromix-db
    databaseName: teromix
    user: teromix 