services:
  - type: web
    name: teromix-strapi
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        value: your-database-host
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: your-database-name
      - key: DATABASE_USERNAME
        value: your-database-username
      - key: DATABASE_PASSWORD
        value: your-database-password
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: ADMIN_JWT_SECRET
        value: your-admin-jwt-secret
      - key: API_TOKEN_SALT
        value: your-api-token-salt
      - key: DATABASE_SSL
        value: "true" 